<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailAddresstxt</name>
   <tag></tag>
   <elementGuidId>d10e8bd3-de26-4e9c-9f36-50ea1616efbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#logonIdentifier</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
