<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passtxt</name>
   <tag></tag>
   <elementGuidId>eea047a1-2219-46f6-89b3-9d5193c657dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#password</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
