<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>signInbtn</name>
   <tag></tag>
   <elementGuidId>e5858b81-c3b4-4375-a84b-77e7b3709506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button#next</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
