<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnCancel</name>
   <tag></tag>
   <elementGuidId>16a74922-beb9-4135-807e-c0afca43f387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-secondary</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
