<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropBusinessAddress_Country</name>
   <tag></tag>
   <elementGuidId>8806e280-8557-4a86-b427-721cf84bbe1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#mat-input-76</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
