<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MenuObjects</name>
   <tag></tag>
   <elementGuidId>647ea10f-c522-424c-a069-a6e75a317a6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav-side-nav//*[contains(text(),'${MenuName}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[href='${MenuLink}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
