<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubmenuObjects_Hover</name>
   <tag></tag>
   <elementGuidId>b3d0b142-03b1-40b1-8d8c-e754f3e2db04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[href='${SubmenuLink}']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li/a[contains(text(),'${SubmenuName}')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
