<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnBusinessAddress</name>
   <tag></tag>
   <elementGuidId>1dbe40c6-7115-4571-bba2-2fcae67343c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.input-wrap</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
