<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnBusinessAddress_Cancel</name>
   <tag></tag>
   <elementGuidId>19368ff8-26f1-4110-a311-c43e58bccdf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.mat-dialog-actions>button.button-secondary</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
